dist: trusty
language: java
jdk:
- openjdk8
script: "./gradlew build"
deploy:
  provider: releases
  api_key:
    secure: k+5jX/BES4DhcZK5gatvOu+SXQiyzbBGHhO+gCBGJccHSx8T/SrXVbXcmIZ3IQtpZvlRn3JVFhmhEcXkT5DUj60xqaoHW01G7IPntOruO52VKsGs0jpLKBJyf4DZjT0hhdfUqazpdq3sSxsyaetjElbsCMsMRdbVHZwcJFR1lSdmVp7Th5gDAISy3IVz5don/OGf2Q6bkOm92VAUFgtmWazo/NRTA4kqiBZr6R7GaLKZ9voVaimB6TD+kTgnIv3i98qqJAs9NQ4xPKwHWy67wsvAla5+QFYMmKvW6294P8+be5tgGm4KXg1AWyDJmNNL1rRJutI+u6URjznWxMHKuC2zqRi9NND33Corw5L+Zf7s4rmR1RaeQktwZQ3moW1Q4bUnGx1ZCrsqMwDntcZchKsDRLwz8O51qYNaTVjknZ3s7dsMDlkiQaYzLbcBRT9e8jIM9vgQnbxQrQRClTELNUmencFvzfD2YraDgLhT/Lsbpl/1hVjzsujLyELb88tn0RktcHaQ9XMUzkBM6O4Zz7HG4o1SvuPTT20YVyJSR04JytJKYUMilVUaRjTIw2GA9v0wOUrNMJiBlfCdw75/L/6TAfzT8FPpFrJyhtFmbkx+CEoJ1E8wiVuzmlHi9QZUIexyQw5fFBCTx5TLbvisyLvR4DtViWpbCpWvy9DxtSI=
  file: ./build/libs/VoxelSniper-*.jar
  on:
    repo: edewit/VoxelSniper
    branch: sponge-1.12
